# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/.Xil/Vivado-3668-Tyler_Thinkpad/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Adder_16.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Adder_32.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Adder_4.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerDecoder.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerSelector_4digitsToOutput.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerSelector_LEDvisualizer.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerSelector_getCode.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorCalculation.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorDataCollector.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSegDisplay.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorStageSelector.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/FourBit_ToHex.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Multiplier_16.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/NumberDecoder_upto8HexDigits.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/OperationDecoder.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/SevenSeg_4digitDriver.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Subtractor_16_with_negatives.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Subtractor_4.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/anode_clock.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/bitAdder.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/bitsubtractor.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/debouncer.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/decoder.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/dff.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_8bit/dff_16.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/mux.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/mux4b.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_8bit/not_8.v
      C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSource.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top CalculatorSource
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    set_param edifin.funnel true
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/.Xil/Vivado-3668-Tyler_Thinkpad/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
