# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/LatestVivadoTest.runs/synth_1/CalculatorSource.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/LatestVivadoTest.cache/wt [current_project]
set_property parent.project_path C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/LatestVivadoTest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/LatestVivadoTest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Adder_16.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Adder_32.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Adder_4.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerDecoder.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerSelector_4digitsToOutput.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerSelector_LEDvisualizer.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/AnswerSelector_getCode.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorCalculation.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorDataCollector.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSegDisplay.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorStageSelector.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/FourBit_ToHex.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Multiplier_16.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/NumberDecoder_upto8HexDigits.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/OperationDecoder.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/SevenSeg_4digitDriver.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Subtractor_16_with_negatives.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/Subtractor_4.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSevenSeg_dependencies/anode_clock.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/bitAdder.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/Calculation_dependencies/bitsubtractor.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/debouncer.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/decoder.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/dff.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_8bit/dff_16.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/mux.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_EECE251_provided/mux4b.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/ops_8bit/not_8.v
  C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/CalculatorSource.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/FinalProject_Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/FinalProject_Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/tyler/Documents/GitHub/EECE251_FinalProject_VerilogModules/LatestVivadoTest/LatestVivadoTest.srcs/utils_1/imports/synth_1/AnswerSelector_FullTestSource.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top CalculatorSource -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CalculatorSource.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CalculatorSource_utilization_synth.rpt -pb CalculatorSource_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
